image: node:6.11.5
services: 
  - docker:dind 

variables:
  CONTAINER_TEST_IMAGE: registry.pimpmyowl.com/la-bete-politique/la-bete-politique:latest
  DOCKER_DRIVER: overlay2

stages:
  - debug
  - unit
  - package
  - build
  - deploy

.deps_template: &deps
  before_script:
    - apt-get update
    - apt-get install -y apt-transport-https ca-certificates
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt-get update
    - apt-get install -y yarn
    - yarn install
    - yarn cache dir
  cache:
    paths:
      - /root/.cache/yarn/

.tests_template: &tests
  script:
    - yarn test

debug:
  image: docker:latest
  stage: debug
  script:
    - docker info

unit:current:
  image: node:8.8.1
  stage: unit
  <<: *deps
  <<: *tests

unit:lts:
  stage: unit
  <<: *deps
  <<: *tests

package:assets:
  stage: package
  script:
    - yarn run build
  artifacts:
    paths:
      - build/*
  <<: *deps

build:
  image: docker:latest
  stage: build
  script:
    - docker build --file="Dockerfile" --tag="$CONTAINER_TEST_IMAGE" .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_TEST_IMAGE

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  only:
    - develop
  script:
    - upgrade --environment $RANCHER_ENV --stack $RANCHER_STACK --service $RANCHER_SERVICE --rancher-url $RANCHER_URL --no-start-before-stopping --no-wait-for-upgrade-to-finish
