language: node_js

node_js:
  - "10.16.3"
  - "12.10.0"

cache: yarn

script:
  - npm test
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  local_dir: public
  script: "npx now alias $(npx now -t $NOW_TOKEN) $TRAVIS_PULL_REQUEST_BRANCH"
  on:
    branch: /feature\/.*/

notifications:
  slack: augora:NbzHhCF6cj1DOJhe8lGOg5ih
