language: node_js
node_js:
  - "8.11.1"
  - "10.0.0"
after_success:
  - yarn global add codecov
  - codecov
script: yarn run build 
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
cache: yarn
notifications:
  slack: labetepolitique-team:NbzHhCF6cj1DOJhe8lGOg5ih
