name: CI Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ matrix.os }}-yarn-

      - name: yarn install
        env:
          CI: "true"
          NODE_ENV: "pull_request"
          NEXT_PUBLIC_ENV: "pull_request"
        run: yarn install

      - name: yarn build
        env:
          CI: "true"
          NODE_ENV: "pull_request"
          NEXT_PUBLIC_ENV: "pull_request"
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL_STAGING }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_STAGING }}
        run: yarn build

      - name: The build has failed
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":thunder_cloud_and_rain:",
              attachments: [
                {
                  color: '#dc3545',
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": `Le build est en erreur :fire::fire_engine:\nCommit : ${process.env.AS_COMMIT}\nGitHub Action : ${process.env.AS_WORKFLOW}`,
                      },
                      "accessory": {
                        "type": "image",
                        "image_url": "https://i.imgur.com/skVMabZ.png",
                        "alt_text": "Augora"
                      }
                    }
                  ]
                }
              ]
            }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_AUGORA_ORGID }}
          vercel-project-id: ${{ secrets.VERCEL_AUGORA_PROJECTID }}
          vercel-project-name: augora
          alias-domains: |
            {{PR_NUMBER}}.pullrequests.augora.fr

      - name: The build has failed
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":thunder_cloud_and_rain:",
              attachments: [
                {
                  color: '#dc3545',
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": `Le build est en erreur :fire::fire_engine:\nCommit : ${process.env.AS_COMMIT}\nGitHub Action : ${process.env.AS_WORKFLOW}`,
                      },
                      "accessory": {
                        "type": "image",
                        "image_url": "https://i.imgur.com/skVMabZ.png",
                        "alt_text": "Augora"
                      }
                    }
                  ]
                }
              ]
            }
