name: CI Pull Request

on: pull_request

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: yarn install, build
        env:
          CI: "true"
          NODE_ENV: "pull_request"
          GATSBY_TARGET_ENV: "pull_request"
          FAUNADB_TOKEN: ${{ secrets.FAUNADB_TOKEN_STAGING }}
        run: |
          yarn install
          yarn run build

      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          scope: augora
