name: CI Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Virtual envs : https://help.github.com/en/articles/virtual-environments-for-github-actions
        os: [macOS-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 13.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install, build, and test
        env:
          CI: "true"
          NODE_ENV: "pull_request"
          TARGET_ENV: "pull_request"
          FAUNADB_TOKEN: ${{ secrets.FAUNADB_TOKEN }}
        run: |
          yarn install
          yarn run build
          yarn test

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.os }}-${{ matrix.node-version }}
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v1
        with:
          name: build-ubuntu-latest-13.x
          path: public/

      - uses: amondnet/now-deployment@v2
        env:
          BRANCH: ${{ github.base_ref }}
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          now-org-id: ${{ secrets.ORG_ID }} #Required
          zeit-team-id: ${{ secrets.ORG_ID }} #Required
          now-project-id: ${{ secrets.PROJECT_ID }} #Required
