name: Push CI/CD Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: yarn install
        env:
          CI: "true"
          NODE_ENV: "production"
          GATSBY_TARGET_ENV: "production"
        run: yarn install

      - name: yarn build
        env:
          CI: "true"
          NODE_ENV: "production"
          GATSBY_TARGET_ENV: "production"
          FAUNADB_TOKEN: ${{ secrets.FAUNADB_TOKEN_READONLY_PRODUCTION }}
          GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY: 50
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        run: yarn build

      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.ZEIT_ORGID_AUGORA }}
          vercel-project-id: ${{ secrets.ZEIT_PROJECTID_AUGORA }}
          scope: augora
          alias-domains: |
            augora.fr

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":rocket:",
              attachments: [
                {
                  color: '${{ job.status }}' === 'success' ? '#28a745' : '${{ job.status }}' === 'failure' ? '#dc3545' : '#ffc107',
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": '${{ job.status }}' === 'success' ? ':rocket: ----- :tada: ----- :fire: ----- *MISE EN PRODUCTION* ----- :fire: ----- :tada: ----- :rocket:' : ':male-firefighter: ----- :fire_engine: ----- :fire: ----- *MISE EN PRODUCTION* ----- :fire: ----- :fire_engine: ----- :female-firefighter:'
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": '${{ job.status }}' === 'success' ? '*https://augora.fr* \n Messieurs vous avez accompli un travail incroyable. :muscle: \n C\'est toute la société française qui vous remercie aujourd\'hui :bow: \n N\'oubliez pas de vérifier que vos changements sont effectifs :heart:' : 'Le déploiement est en échec :fire::fire_engine: \n Il faut tout recommencer... :crying_cat_face:\n Préparez vous à devoir hotfix toute la nuit :lul:'
                      },
                      "accessory": {
                        "type": "image",
                        "image_url": "https://augora.fr/icons/icon-512x512.png",
                        "alt_text": "Augora"
                      }
                    },
                    {
                      "type": "divider"
                    }
                  ]
                }
              ]
            }
