name: Schedule CI/CD Production

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_AUGORA_ORGID }}
          vercel-project-id: ${{ secrets.VERCEL_AUGORA_PROJECTID }}
          vercel-project-name: augora
          vercel-args: --prod --force
          alias-domains: |
            augora.fr
