name: Schedule CI/CD Production

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_AUGORA_ORGID }}
          vercel-project-id: ${{ secrets.VERCEL_AUGORA_PROJECTID }}
          vercel-project-name: augora
          vercel-args: --prod --force
          alias-domains: |
            augora.fr

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: custom
          fields: workflow,job,commit
          custom_payload: |
            {
              username: "Github Actions",
              icon_emoji: ":rocket:",
              attachments: [
                {
                  color: '${{ job.status }}' === 'success' ? '#28a745' : '${{ job.status }}' === 'failure' ? '#dc3545' : '#ffc107',
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": '${{ job.status }}' === 'success' ? ':rocket: ----- :tada: ----- :clock8: ----- *DEPLOIEMENT QUOTIDIEN* ----- :clock8: ----- :tada: ----- :rocket:' : ':male-firefighter: ----- :fire_engine: ----- :fire: ----- *DEPLOIEMENT QUOTIDIEN* ----- :fire: ----- :fire_engine: ----- :female-firefighter:'
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": '${{ job.status }}' === 'success' ? '*https://augora.fr* \n Données mises à jour \n N\'oubliez pas de vérifier que le site fonctionne toujours :heart:' : 'Le déploiement est en échec :fire::fire_engine: \n Possible que ce soit une erreur FaunaDB (relancer le build) :arrows_counterclockwise:'
                      },
                      "accessory": {
                        "type": "image",
                        "image_url": '${{ job.status }}' === 'success' ? "https://i.imgur.com/WsKz4jX.png" : "https://i.imgur.com/xGJqCp8.png",
                        "alt_text": "Augora"
                      }
                    },
                    {
                      "type": "divider"
                    }
                  ]
                }
              ]
            }
